-- @description Dirt Scripts
-- @author Fleeesch
-- @version 2.2
-- @metapackage
-- @provides
--   [nomain]   Dirt Scripts/_dirt_functions
--   [nomain]   Image.bmp > ColorThemes/Image.bmp
--   [main]     Dirt Scripts/*.lua