-- @description Dirt Scripts
-- @author Fleeesch
-- @version 1.3
-- @metapackage
-- @provides
--    Dirt Scripts/_dirt_functions
--   [main] Dirt Scripts/Fleeesch - Dirt - Load Set 1.lua
--   [main] Dirt Scripts/Fleeesch - Dirt - Load Set 2.lua
--   [main] Dirt Scripts/Fleeesch - Dirt - Load Set 3.lua
--   [main] Dirt Scripts/Fleeesch - Dirt - Load Set 4.lua
