@description Dirt
@version 1
@author Fleeesch
@about
    A theme made with multi-generational display-comaptability in mind. More data on less pixels.
@provides
    Dirt (Git) - Dark (Windows 10).ReaparThemeZip https://github.com/Fleeesch/DiRT/releases/download/Release/Dirt.-.Dark.-.Win.10.ReaperThemeZip
    Dirt (Git) - Dark.ReaparThemeZip https://github.com/Fleeesch/DiRT/releases/download/Release/Dirt.-.Dark.ReaperThemeZip  
    Dirt (Git) - Light.ReaparThemeZip https://github.com/Fleeesch/DiRT/releases/download/Release/Dirt.-.Light.ReaperThemeZip
    
@links
    Github Repository https://github.com/Fleeesch/DiRT
@changelog
    Minor Changes